### ISSUE TITLE
Writing a message to get chat id does not work. 

### ISSUE THREAD

**Issue by elblogbruno** [luke5sky/telegram-skill#11]
Writing a message to get chat id does not work. I've set the bot token on settings ( did update to latest version that fixes that settings did not appear). I'm having this error shown on the mycroft-cli.
![image](https://user-images.githubusercontent.com/10481058/78659359-b8106d80-78cb-11ea-8196-6d51ea020b46.png)
Thanks

**Comment by elblogbruno** [comment]
I fixed it by simply changing the int to a string with str(self.chat_id)

**Comment by luke5sky** [comment]
thank you, should be fixed now, if you could test it, that would be great

**Comment by luke5sky** [comment]
Closing this issue, this should be fixed.
