### ISSUE TITLE
Using skill that returns multiple responses only passes first one to the telegram bot.

### ISSUE THREAD

**Issue by Void-Seeker** [luke5sky/telegram-skill#20]
Using skill that returns multiple responses (For example, weather skill) only passes first one to the telegram bot. Others will go to the standard output only.

**Comment by luke5sky** [comment]
Hi, that is a known issue, unfortunately I got no time to fix this at the moment.

**Comment by luke5sky** [comment]
i will look into this after my Mark II arrives (hopefully end of this year)

**Comment by lcipria** [comment]
Hi everyone!
I found another issue (maybe related to this one): using reminder skill is impossible via telegram (you'll never be prompted to take any action).
It seems to me a messagebus-related issue (weather/reminder skill have no idea of the source of the request; neither this skill is supposed to relay any single dialog spoken by mycroft)... But that’s just my two cents.

P.S. thanks to @luke5sky for this skill

**Comment by luke5sky** [comment]
@lcipria i appreciate the feedback. Will look into this when my mark II arrives

**Comment by luke5sky** [comment]
As mycroft is going out of business and i never got my mark II there will be no further development for this skill
