### ISSUE TITLE
Calling the bot in a Telegram group means the /<botname> becomes part of the text sent to Mycroft

### ISSUE THREAD

**Issue by katoog** [luke5sky/telegram-skill#22]
When the Telegram bot is added to a group and the group ID is specified in the Mycroft Telegram skills configuration, it's possible for users to send Mycroft commands by typing "/botname what is the time" in the Telegram group. The issue is that Mycroft interprets the "/botname" as part of the question which confuses it.

```
00:39:47.217 | INFO     |   778 | telegram_luke5sky | Telegram-Message from User: /TestingzMycroftBot what is a turtle
00:39:47.395 | INFO     |   778 | QuestionsAnswersSkill | Searching for /testingzmycroftbot what is a turtle?
00:39:47.406 | INFO     |   778 | WolframAlphaSkill | WolframAlpha query: /testingzmycroftbot what is a turtle?
00:39:48.940 | INFO     |   778 | fallback-wolfram-alpha_mycroftai.skill.wolfram_client:get_spoken_answer:278 | No answer available from Wolfram Alpha.
00:39:49.102 | INFO     |   778 | QuestionsAnswersSkill | Timeout occured check responses
00:39:49.651 | INFO     |   778 | telegram_luke5sky | Sending to Telegram-User: I don't know what that means.
```
Is it possible for the Telegram skill to strip out the /botname part from the text before sending it to Mycroft?

**Comment by luke5sky** [comment]
Hi,

i am not actively developing this skill until my Mark II arrives (hopefully at the of this year).
However, you may try to add the following in __init__.py between lines 133 and 134:

`if msg.startswith('/PUTYOURBOTNAMEHERE') : `
`   msg = msg.replace('/PUTYOURBOTNAMEHERE ', '')`
`else:`
`   pass`

the whole function should then look something like this:
![grafik](https://user-images.githubusercontent.com/27992191/180965957-e56597c1-e4c4-4190-87c5-7a713a3bc7a5.png)

be aware, i cannot test this at the moment, so it may not work.

regards

**Comment by katoog** [comment]
Thank you for your effort on the skills and your detailed reply above. I'll try it out when I get some free time in the next couple of days and report back!

**Comment by katoog** [comment]
Reporting back to say that it worked perfectly. Thank you!
Close the issue or leave open to implement in future version, maybe as a skill setting to pass the bot name from mycroft.ai?

**Comment by luke5sky** [comment]
I forgot to answer you:
Thank you for your feedback, glad to hear it worked.
I will definitely implement this, shouldn't be very difficult to do this.

**Comment by luke5sky** [comment]
As mycroft is going out of business and i never got my mark II there will be no further development for this skill
